name: spellcheck
on: push
jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GitHub Spellcheck Action
        uses: rojopolis/spellcheck-github-actions@0.28.0
        with:
          config_path: .spellcheck.yml
          task_name: Markdown